apiVersion: v1
kind: Service
metadata:
  name: cost-living-platform-api
  namespace: cost-living
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
spec:
  selector:
    app: cost-living-platform-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
