apiVersion: v1
kind: Secret
metadata:
  name: cost-living-platform-api-secrets
  namespace: cost-living
type: Opaque
stringData:
  ELASTICSEARCH_URL: "https://elasticsearch-es-http.elastic.svc:9200"
  ELASTICSEARCH_USERNAME: "elastic"
  ELASTICSEARCH_PASSWORD: "replace-with-elasticsearch-es-elastic-user-secret"
  ELASTICSEARCH_VERIFY_CERTS: "false"
